<?php


namespace Encore\OrgRbac\Http\Controllers;


use Encore\OrgRbac\Layout\Content;
use Encore\OrgRbac\Form;
use Encore\OrgRbac\Models\Enums\OrgType;
use Encore\OrgRbac\Traits\PlatformPermission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CompanyController extends AdminController
{
    use PlatformPermission;

    /**
     * Title for current resource.
     *
     * @var string
     */
    protected $title = '公司';

    protected $model;

    protected $parentId;


    /**
     * @var
     */
    protected $service;

    public function __construct(Request $request)
    {
        $model = config('org.database.companies_model');
        $this->model = new $model();
        parent::__construct($request);
        $this->platformId = $request->input('platform_id');
        $this->parentId = $request->input('parent_id');
    }

    public function edit($id, Content $content)
    {
        session()->put('company_back_url',request()->get('back_url'));
        return parent::edit($id, $content); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    protected function form($request = '')
    {
        $platformModel = config('org.database.platforms_model');
        $form = new Form($this->model);

        $form->select('platform_id', '平台')
            ->options($platformModel::pluck('name','id'))
            ->default($this->getPlatformId())
            ->required()->disable();
        $form->hidden("platform_id",'平台ID')->value($this->getPlatformId());
        $form->select('parent_id',"父级公司")
            ->options(config('org.database.companies_tree')::selectOptions(function ($query) {
                return $query->where('platform_id',$this->getPlatformId());
            }))
            ->default($this->parentId)
            ->required();
        $form->text('name', '名称')->required();
        $form->number('order','排序')->default(0)->required();

        $form->saving(function (Form $form) {
            if ($form->isCreating()) $form->model()->id = app('primaryKeyGenerate')->load(config('org.database.companies_primary_key_generate_driver'))->generate();
            if (empty($form->model()->parent_id)) $form->model()->parent_id = 0;
        });
        $form->saved(function (Form $form) use($request){
            if ($form->isEditing()) $backUrl = $this->getBackUrl();
            if ($form->isCreating()) $backUrl = url("admin/auth/organizations")."?type=".OrgType::COMPANY."&main_id=".$form->model()->parent_id;
            return redirect($backUrl)->withErrors(admin_toastr('已保存','success'));
        });
        return $form;
    }

    protected function getBackUrl()
    {
        $backUrl = session()->pull('company_back_url');
        $backUrl = base64_decode($backUrl);
        if (!$backUrl) $backUrl = url('admin/auth/organizations');
        return $backUrl;
    }

    public function destroy($id)
    {
        $trans = [
            'failed'    => trans('admin.delete_failed'),
            'succeeded' => trans('admin.delete_succeeded'),
        ];
        try {
            DB::transaction(function () use ($id) {
                //判断当前ID是否存在
                $model = $this->model->find($id);
                if (empty($model)) {
                    throw new \Exception("the current company does not exist");
                }
                //判断当前公司下是否有部门
                if ($model->departments()->exists()) {
                    throw new \Exception("there are departments under the current company");
                }
                $this->model->where('id',$id)->delete();
            });
            return $this->actionSuccess($trans['succeeded']);
        } catch (\Exception $exception) {
            return $this->actionError("{$trans['failed']} : {$exception->getMessage()}");
        }
    }

}
