<?php


namespace Encore\OrgRbac\Http\Controllers;

use Encore\OrgRbac\Layout\Content;
use Encore\OrgRbac\Form;
use Encore\OrgRbac\Models\Enums\DepartmentType;
use Encore\OrgRbac\Traits\PlatformPermission;
use Illuminate\Http\Request;

class DutyController extends AdminController
{
    use PlatformPermission;
    /**
     * Title for current resource.
     *
     * @var string
     */
    protected $title = '职权';


    protected $model;

    protected $platformId;

    /**
     * @var
     */
    protected $service;

    public function __construct(Request $request)
    {
        $model = config('org.database.duties_model');
        $this->model = new $model();
        parent::__construct($request);
    }

    public function create(Content $content)
    {
        session()->put('duty_back_url',$this->request->get('back_url'));
        return parent::create($content); // TODO: Change the autogenerated stub
    }

    public function edit($id, Content $content)
    {
        $this->platformId = $this->model->find($id)->department->company->platform->id;
        session()->put('duty_back_url',$this->request->get('back_url'));
        return parent::edit($id, $content); // TODO: Change the autogenerated stub
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    public function form()
    {
        $roleModel = config('org.database.roles_model');
        $form = new Form($this->model);
        $form->display('user.name','用户');
        $form->display('department.name','部门');
        $form->select('department_type','类型')->options(DepartmentType::$text);
        $form->listbox('roles','角色')->options($roleModel::getPlatformRole($this->getPlatformId()));
        $form->saved(function (Form $form) {
            $backUrl = $this->getBackUrl();
            return redirect($backUrl)->withErrors(admin_toastr('已保存','success'));
        });
        return $form;
    }

    protected function getBackUrl()
    {
        $backUrl = session()->pull('duty_back_url');
        $backUrl = base64_decode($backUrl);
        if (!$backUrl) $backUrl = url('admin/auth/organizations');
        return $backUrl;
    }

}
